[package]
name = "maxba/dojo-obby"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]
Fusion = "elttob/fusion@0.2.0"
Trove = "sleitnick/trove@0.5.0"
Component = "sleitnick/component@2.4.6"
Promise = "evaera/promise@4.0.0"
Rewire = "sayhisam1/rewire@0.3.0"
Red = "uncontained0/red@^1.0.0"

[server-dependencies]
ProfileService = "firecam702/profileservice@1.0.0"