[package]
name = "maxba/dojo-obby"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]
Knit = "sleitnick/knit@^1.4"
Fusion = "elttob/fusion@0.2.0"
Trove = "sleitnick/trove@0.5.0"
Signal = "sleitnick/signal@1.5.0"
Component = "sleitnick/component@2.4.6"
BezierTween = "max-bacon/bezier-tweens@1.1.1"

[server-dependencies]
ProfileService = "firecam702/profileservice@1.0.0"