[package]
name = "maxba/dojo-obby"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]
Knit = "sleitnick/knit@^1.4"
Roact = "roblox/roact@1.4.4"
Rodux = "roblox/rodux@4.0.0-rc.0"
ReplicaService = "brittonfischer/replicaservice@0.1.0"

[server-dependencies]
ProfileService = "firecam702/profileservice@1.0.0"