-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	UI = {
		CheckpointText = "rbxassetid://13118066777",
		Katana = "rbxassetid://13074066045",
		SkipBackground = "rbxassetid://13764274301",
		SkipText = "rbxassetid://13764274398",
	},
}