name: Deploy Dev (Lync)

on:
  push:
    branches:
    - dev

jobs:

  deploy:
    name: Deploy
    runs-on: windows-latest
    steps:
    - run: dir

    - name: Install Node.js
      uses: actions/setup-node@v3

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Checkout Lync
      uses: actions/checkout@master
      with:
        repository: Iron-Stag-Games/Lync
        path: Lync
        ref: latest

    - run: dir -r

    - uses: ok-nick/setup-aftman@v0.3.0
      name: Install Aftman
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - run: wally install

    - run: node "Lync/Lync/index.js" default.project.json OFFLINE

    - run: rbxcloud experience publish -f BuildScripts/Build/Build.rbxl -p ${{ secrets.DEV_PLACE_ID }} -u ${{ secrets.DEV_UNIVERSE_ID }} -t published -a ${{ secrets.API_KEY }}