name: Deploy Dev (Lync)

on:
  push:
    branches:
    - dev

jobs:

  deploy:
    name: Deploy
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
    uses: actions/setup-node@v3

    

    - uses: ok-nick/setup-aftman@v0.3.0
      name: Install Aftman
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Lync


    - run: wally install

    - run: ./BuildScripts/Win_BuildOffline.bat

    - run: rbxcloud experience publish -f ./BuildScripts/Build/Build.rbxl -p ${{ secrets.DEV_PLACE_ID }} -u ${{ secrets.DEV_UNIVERSE_ID }} -t published -a ${{ secrets.API_KEY }}