name: Deploy Dev

on:
  push:
    branches:
    - dev
    # paths:
    # - 'src/**'
    # - 'wally.toml'

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:

    - name: Download Repository
      uses: actions/checkout@master

    - name: Extract Project
      run: |
        mv Lync/ ../LyncBinaries/
        mv "dojo-obby/" ../temp/
        rm -r *
        mv -v ../temp/* ./

    - name: Aftman Install
      uses: ok-nick/setup-aftman@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install Wally Packages
      run: wally install

    - name: Build
      run: |
        ../LyncBinaries/lync-linux-x64 BUILD lync.project.json

    - name: Publish
      run: rbxcloud experience publish -f "BuildScripts/Build/Build.rbxl" -p ${{ secrets.PLACE_ID }} -u ${{ secrets.EXPERIENCE_ID }} -t published -a ${{ secrets.API_KEY }}