name: Deploy Dev

on:
  push:
    branches:
    - dev
    # paths:
    # - 'src/**'
    # - 'wally.toml'

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:

    - name: Download Repository
      uses: actions/checkout@master

    - name: Aftman Install
      uses: ok-nick/setup-aftman@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install Wally Packages
      run: wally install

    - name: Lync Build
      run: lync build lync.project.json

    - name: Publish
      run: rbxcloud experience publish -f BuildScripts/Build/Build.rbxl -p ${{ secrets.DEV_PLACE_ID }} -u ${{ secrets.DEV_UNIVERSE_ID }} -t published -a ${{ secrets.API_KEY }}